spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/${mysqldbname:rocket}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: ${mysqlpasswd:xp8bEGK3GAG6a8pd}
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: always
#      continue-on-error: true


  mail:
    host: smtp.qq.com
    username: ${sendmailaddress:ss@qq.com}
    password: ${sendmailpasswd:yxwrnwnxvtssdagd}
